name: ccmultiomkge
channels:
  # - bioconda
  # - conda-forge
dependencies:
  - python=3.9
  - pip
  - r-base=4
  - numpy #ALLarch
  - pandas  #ALLarch
  - scikit-learn  #ALLarch
  - pytorch::pytorch
  - bioconda::scprep #noarch
  - rpy2 #ALL64arch
  - r-tidyverse  #noarch
  - conda-forge::r-seurat
  - pip:
    - pykeen
