name: collab
channels:
  - conda-forge
dependencies:
  - python=3.9.*
  - pip
  - r-base=4.*
  - r-tidyverse=1.3.*
  - r-seurat=4.1.*
  - bioconda::bioconductor-singlecellexperiment
  - conda-forge::rpy2 #This works!
  - jupyter
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - cudatoolkit=11.3.*
  - tensorflow
  - keras
  - pip:
    - numpy
    - pandas
    - notebook
    - scanpy
    - networkx
    - pykeen
    - scikit-learn
    - phate
    - scipy
    - scprep
    - DiffusionEMD
    - meld
    - matplotlib
    - seaborn
    - anndata2ri
    - biomart
    - magic-impute
